sudo: false

language: node_js
node_js:
- "8.11.3"

cache:
  directories:
    - node_modules

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - npm install -g eslint codacy-coverage

before_script:
  - meteor npm install

script:
  - meteor npm test
  - meteor npm run lint
  - sed .coverage/lcov.info | codacy-coverage
